# Use Python 3.11 slim image as the base
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /code_snippet

# Copy the Flask application code into the container
COPY . /code_snippet

# Copy the requirements.txt file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port on which your Flask application runs (assuming port 5001)
EXPOSE 5001

# Command to run the Flask application
CMD ["python", "main.py"]
